/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Size = IDL.Record({ 'name' : IDL.Text, 'available' : IDL.Bool });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'originalPrice' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'selectedSize' : IDL.Text,
  'product' : Product,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Vec(Size),
        IDL.Float64,
      ],
      [],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'checkout' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], []),
  'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'initializeDefaultProducts' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateProductRating' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Size = IDL.Record({ 'name' : IDL.Text, 'available' : IDL.Bool });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'originalPrice' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({
    'quantity' : IDL.Nat,
    'selectedSize' : IDL.Text,
    'product' : Product,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Vec(Size),
          IDL.Float64,
        ],
        [],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'checkout' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], []),
    'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initializeDefaultProducts' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateProductRating' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };