/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'quantity' : bigint,
  'selectedSize' : string,
  'product' : Product,
}
export interface Product {
  'id' : bigint,
  'originalPrice' : [] | [number],
  'name' : string,
  'description' : string,
  'sizes' : Array<Size>,
  'imageUrl' : string,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : number,
}
export interface Size { 'name' : string, 'available' : boolean }
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      [] | [number],
      string,
      Array<Size>,
      number,
    ],
    undefined
  >,
  'addToCart' : ActorMethod<[bigint, bigint, string], undefined>,
  'checkout' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], number>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductCount' : ActorMethod<[], bigint>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'initializeDefaultProducts' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[bigint, string], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateProductRating' : ActorMethod<[bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];